version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  # Job to build and test the project
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report

  # Job to upload coverage to Codecov
  upload-codecov:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  upload-to-codecov:
    jobs:
      - build-and-test
      - upload-codecov