version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  # Job to build and test the project
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

  # Job to generate and deploy Javadoc
  generate-and-deploy-javadoc:
    docker:
      - image: cimg/openjdk:21.0
    steps:
      - checkout
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            # Configure Git
            git config --global user.email "kechadifarid10@gmail.com"
            git config --global user.name "kechadifarid"
            # Clone the gh-pages branch with the token
            git clone --branch gh-pages https://$GH_TOKEN@github.com/kechadifarid/ceri-m1-techniques-de-test.git gh-pages
            # Copy the Javadoc
            rm -rf gh-pages/*
            cp -r target/site/apidocs/* gh-pages/
            # Commit and push changes
            cd gh-pages
            git add .
            git commit -m "Update Javadoc [ci skip]"
            git push https://$GH_TOKEN@github.com/kechadifarid/ceri-m1-techniques-de-test.git gh-pages

workflows:
  upload-to-codecov-and-deploy-javadoc:
    jobs:
      - build-and-test
      - generate-and-deploy-javadoc:
          requires:
            - build-and-test
