version: 2.1
jobs:
  test-java:
    docker:
      - image: cimg/openjdk:11.0  # Utilisez Java 11
    steps:
      - checkout
      - run:
          name: Calculate cache key
          command: |-
            find . -name 'pom.xml' -o -name 'gradlew*' -o -name '*.gradle*' | \
                    sort | xargs cat > /tmp/CIRCLECI_CACHE_KEY
      - restore_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
      - run:
          command: mvn verify  # Exécution des tests unitaires avec Maven
      - store_test_results:
          path: target/surefire-reports
      - save_cache:
          key: cache-{{ checksum "/tmp/CIRCLECI_CACHE_KEY" }}
          paths:
            - ~/.m2/repository

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'  # Remplacer par les étapes réelles de déploiement

workflows:
  build-and-test:
    jobs:
      - test-java
      - deploy:
          requires:
            - test-java
          filters:
            branches:
              only: master  # Branche master uniquement
