version: 2.1

orbs:
  codecov: codecov/codecov@4.0.1

jobs:
  # Job to build and test the project
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout  # Récupère le code source dans le répertoire de travail
      - run:
          name: Run Tests
          command: mvn test
      - run:
          name: Generate Coverage Report
          command: mvn jacoco:report
      - run:
          name: Upload Coverage to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc

  # Job to deploy Javadoc to GitHub Pages
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout  # Clone le repository
      - run:
          name: Install gh-pages
          command: npm install -g --silent gh-pages@2.0.1
      - run:
          name: Configure Git
          command: |
            git config user.email "lyes.douki@alumni.univ-avignon.fr"
            git config user.name "lyesdki"
      - run:
          name: Clone gh-pages Branch
          command: |
            git clone --branch gh-pages https://$GH_TOKEN@github.com/kechadifarid/ceri-m1-techniques-de-test.git gh-pages
      - run:
          name: Copy Javadoc
          command: |
            rm -rf gh-pages/*
            cp -r target/site/apidocs/* gh-pages/
      - run:
          name: Commit and Push Javadoc to gh-pages
          command: |
            cd gh-pages
            git add .
            git commit -m "Update Javadoc [ci skip]"
            git push https://$GH_TOKEN@github.com/kechadifarid/ceri-m1-techniques-de-test.git gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - docs-deploy:
          requires:
            - build
