name: Build and Publish Javadoc

on:
  push:
    branches:
      - master  # La branche sur laquelle vous voulez déclencher le workflow
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build project and generate Javadoc
        run: mvn clean javadoc:javadoc

      - name: Publish Javadoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Utilisez le token de votre dépôt pour l'authentification
          publish_dir: target/site/apidocs  # Le dossier où la Javadoc est générée
          publish_branch: gh-pages  # Branche où publier la Javadoc
          user_name: 'GitHub Actions'  # Nom de l'utilisateur
          user_email: 'github-actions[bot]@users.noreply.github.com'  # Email de l'utilisateur
