name: Generate and Deploy Documentation

on:
  push:
    branches:
      - master

permissions:                   # Permissions de lecture et écriture
  contents: write               # Autorise l'accès en écriture pour les actions

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code source
      - name: Checkout repository
        uses: actions/checkout@v4

      # Étape 2 : Setup Java
      - name: Setup Java 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      # Étape 3 : Générer la documentation avec Maven
      - name: Generate JavaDoc
        run: mvn -B javadoc:javadoc

      # Étape 4 : Déploiement sur GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Utilisation de GITHUB_TOKEN pour les permissions d'écriture
          publish_dir: ./target/reports/apidocs